apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "daily-quote-go.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "daily-quote-go.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "daily-quote-go.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
