apiVersion: v1
kind: Service
metadata:
  name: {{ include "daily-quote-go.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "daily-quote-go.name" . }}
    chart: {{ include "daily-quote-go.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port}}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "daily-quote-go.name" . }}
