replicaCount: 1

namespace: default

app:
  name: daily-quote-go
  chart: daily-quote-go-chart

image:
  repository: acrdevdailyquote.azurecr.io/daily-quote-go 

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: rikardo.zip