name: Go

on:
  push:
    branches: [ main, dev, feat/** ]
  pull_request:
    branches: [ main, dev, feat/** ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build
        run: go build -o bin/app ./cmd
      - name: Test
        run: go test ./cmd -v