name: "Pull Request Labeler"
on:
- pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
    - uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GH_PAT }}
        configuration-path: .github/labeler.yml